# Generated by Django 3.0.8 on 2020-09-13 06:15

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=800, max_digits=20)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('sale', models.BooleanField(default=False)),
                ('mens', models.BooleanField(default=False)),
                ('Women', models.BooleanField(default=False)),
                ('kids', models.BooleanField(default=False)),
            ],
        ),
    ]
